# Site settings
title: Stephanie Unger
email: stephanie@ungermail.com
url: http://stepheunger.com
description: "Creator. Of dance, of words, of babies."
skills: "Dancer - Writer - Social Media Guru"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 969696
  secondary: ffffff
  secondary-dark: d94fcf

# Footer settings
footer:
  copyright: Stephanie Unger
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/stepheunger
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'I like bananas.'

# Build settings
markdown: kramdown
permalink: pretty
