# Site settings
title: Stephanie Unger
email: stephanie@ungermail.com
url: "http://stepheunger.com"
description: "Creator. Of dance, of words, of babies."
skills: "Creator. Of dance, of words, of babies."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 999999
  secondary: 333333
  secondary-dark: d94fcf

# Footer settings
# footer:
  # copyright: Stephanie Unger
  # location: Location
  # social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: mail
  #   url: stephanie@ungermail.com
  - title: linkedin
    url: https://www.linkedin.com/in/stepheunger
  - title: twitter
    url: https://twitter.com/stepheunger
  - title: instagram
    url: https://instagram.com/stepheunger
  - title: pinterest
    url: https://pinterest.com/stephunger3

# Build settings
markdown: kramdown
permalink: pretty
